# Generated by Django 2.1 on 2019-09-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'managed': False},
        ),
    ]
