# Generated by Django 2.1 on 2019-09-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190904_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='choice',
            table='polls_choice',
        ),
    ]
